name: IU Workbook Merge
description: Merge your IU Workbook cover, content and bibliography with GitHub Actions.
    
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download PDF Files from GitHub Artifacts.
      uses: actions/download-artifact@v2
    - name: Merge PDF Documents (Cover, Content, Bibliography)
      run: |
        sudo apt-get install pdftk -y  # Merge .pdf
        pdftk cover/cover.pdf content/content.pdf bibliography/bibliography.pdf cat output merge.pdf
      shell: bash
    - name: Upload PDF to GitHub Artifacts
      uses: actions/upload-artifact@master
      with:
        name: merge
        path: merge.pdf
